import base64
import json
import os
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, List, Optional

import requests
import yaml

GITHUB_API = "https://api.github.com"
COMMANDS_INCOMING = Path("commands/incoming")
COMMANDS_PROCESSED = Path("commands/processed")
TOGGLE_PATH = Path("atlas/toggle_state.json")

@dataclass
class Change:
    path: str
    content: str
    mode: str = "overwrite"  # or "append"

@dataclass
class Instruction:
    target_repo: str
    base_branch: str
    branch_name: str
    title: str
    body: str
    changes: List[Change]

def load_toggle_state() -> dict[str, Any]:
    if not TOGGLE_PATH.exists():
        return {
            "atlas_state": "LOCKED",
            "last_actor": "unknown",
            "last_change_utc": datetime.now(timezone.utc).isoformat()
        }
    with TOGGLE_PATH.open("r", encoding="utf-8") as f:
        return json.load(f)

def ensure_allowed() -> None:
    state = load_toggle_state()
    atlas_state = state.get("atlas_state", "LOCKED")
    if atlas_state != "PASS":
        raise SystemExit(f"Atlas state is {atlas_state!r}. Aborting apply_changes.")

def load_instruction_file(path: Path, default_repo: str) -> Instruction:
    if path.suffix.lower() in {".yml", ".yaml"}:
        raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    elif path.suffix.lower() == ".json":
        raw = json.loads(path.read_text(encoding="utf-8"))
    else:
        raise ValueError(f"Unsupported command file type: {path}")

    target_repo = raw.get("target_repo", default_repo)
    base_branch = raw.get("base_branch", "main")
    branch_name = raw.get("branch_name") or f"auto/{path.stem}-{int(datetime.now().timestamp())}"
    title = raw.get("title", f"Automated change from {path.name}")
    body = raw.get("body", "Automated change generated by affynix-automation controller.")

    changes_data = raw.get("changes", [])
    changes: List[Change] = []
    for item in changes_data:
        changes.append(
            Change(
                path=item["path"],
                content=item.get("content", ""),
                mode=item.get("mode", "overwrite"),
            )
        )

    return Instruction(
        target_repo=target_repo,
        base_branch=base_branch,
        branch_name=branch_name,
        title=title,
        body=body,
        changes=changes,
    )

def gh_headers(token: str) -> dict[str, str]:
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

def get_branch_sha(token: str, repo: str, branch: str) -> str:
    url = f"{GITHUB_API}/repos/{repo}/git/ref/heads/{branch}"
    resp = requests.get(url, headers=gh_headers(token), timeout=30)
    resp.raise_for_status()
    return resp.json()["object"]["sha"]

def create_branch(token: str, repo: str, new_branch: str, base_sha: str) -> None:
    url = f"{GITHUB_API}/repos/{repo}/git/refs"
    payload = {
        "ref": f"refs/heads/{new_branch}",
        "sha": base_sha,
    }
    resp = requests.post(url, headers=gh_headers(token), json=payload, timeout=30)
    if resp.status_code not in (201, 422):
        # 422 if branch already exists
        resp.raise_for_status()

def get_file_sha_if_exists(token: str, repo: str, path: str, branch: str) -> Optional[str]:
    url = f"{GITHUB_API}/repos/{repo}/contents/{path}"
    params = {"ref": branch}
    resp = requests.get(url, headers=gh_headers(token), params=params, timeout=30)
    if resp.status_code == 404:
        return None
    resp.raise_for_status()
    data = resp.json()
    if isinstance(data, dict) and "sha" in data:
        return data["sha"]
    return None

def get_file_content_if_exists(token: str, repo: str, path: str, branch: str) -> Optional[str]:
    url = f"{GITHUB_API}/repos/{repo}/contents/{path}"
    params = {"ref": branch}
    resp = requests.get(url, headers=gh_headers(token), params=params, timeout=30)
    if resp.status_code == 404:
        return None
    resp.raise_for_status()
    data = resp.json()
    if isinstance(data, dict) and "content" in data:
        encoded = data["content"]
        return base64.b64decode(encoded).decode("utf-8")
    return None

def put_file(
    token: str,
    repo: str,
    path: str,
    branch: str,
    message: str,
    content: str,
    sha: Optional[str] = None,
) -> None:
    url = f"{GITHUB_API}/repos/{repo}/contents/{path}"
    payload: dict[str, Any] = {
        "message": message,
        "content": base64.b64encode(content.encode("utf-8")).decode("ascii"),
        "branch": branch,
    }
    if sha:
        payload["sha"] = sha

    resp = requests.put(url, headers=gh_headers(token), json=payload, timeout=30)
    resp.raise_for_status()

def create_pull_request(token: str, repo: str, instruction: Instruction) -> None:
    url = f"{GITHUB_API}/repos/{repo}/pulls"
    payload = {
        "title": instruction.title,
        "body": instruction.body,
        "head": instruction.branch_name,
        "base": instruction.base_branch,
    }
    resp = requests.post(url, headers=gh_headers(token), json=payload, timeout=30)
    resp.raise_for_status()

def process_instruction(token: str, instruction: Instruction) -> None:
    base_sha = get_branch_sha(token, instruction.target_repo, instruction.base_branch)
    create_branch(token, instruction.target_repo, instruction.branch_name, base_sha)

    for change in instruction.changes:
        existing_content = None
        existing_sha = get_file_sha_if_exists(
            token,
            instruction.target_repo,
            change.path,
            instruction.branch_name,
        )

        if change.mode == "append" and existing_sha:
            existing_content = get_file_content_if_exists(
                token,
                instruction.target_repo,
                change.path,
                instruction.branch_name,
            )

        if change.mode == "append" and existing_content is not None:
            new_content = existing_content + change.content
        else:
            new_content = change.content

        put_file(
            token=token,
            repo=instruction.target_repo,
            path=change.path,
            branch=instruction.branch_name,
            message=f"Automated update for {change.path}",
            content=new_content,
            sha=existing_sha,
        )

    create_pull_request(token, instruction.target_repo, instruction)

def move_to_processed(path: Path) -> None:
    COMMANDS_PROCESSED.mkdir(parents=True, exist_ok=True)
    target = COMMANDS_PROCESSED / path.name
    path.replace(target)

def main() -> int:
    ensure_allowed()

    token = os.getenv("MONO_REPO_TOKEN")
    if not token:
        print("ERROR: MONO_REPO_TOKEN is not set.")
        return 1

    default_repo = os.getenv("MONO_REPO_FULL_NAME", "Affynix-LLC/mono-repo-master")

    COMMANDS_INCOMING.mkdir(parents=True, exist_ok=True)
    COMMANDS_PROCESSED.mkdir(parents=True, exist_ok=True)

    command_files = sorted(
        p for p in COMMANDS_INCOMING.glob("*")
        if p.is_file() and not p.name.startswith(".")
    )

    if not command_files:
        print("No incoming command files found.")
        return 0

    for path in command_files:
        print(f"Processing command file: {path}")
        try:
            instr = load_instruction_file(path, default_repo)
            process_instruction(token, instr)
            move_to_processed(path)
            print(f"Successfully processed {path}")
        except SystemExit:
            raise
        except Exception as exc:
            print(f"ERROR processing {path}: {exc}")

    return 0

if __name__ == "__main__":
    raise SystemExit(main())
